### ISSUE TITLE
VitTracker weights (request)

### ISSUE THREAD

**Issue by arielkantorovich** [lpylpy0514/workspace_tracking#1]
Hi,
I using VitTracker from opencv zoo I want to say thank you for your contribution. 
I want to ask if you try training on the dataset UAV123 and if you do can you share with me the onnx files?

**Comment by lpylpy0514** [comment]
I didn't trained on UAV123. I just used COCO, trackingnet, lasot and got10k.

**Comment by arielkantorovich** [comment]
Thank you for your answer, In the future you intend to add UAV123?
Another question after training you convert *.pth to *.onnx?

**Comment by lpylpy0514** [comment]
The convert code is in tracking/onnxexport.py. Besides, I don't have a plan about UAV123 dataset for now.

**Comment by arielkantorovich** [comment]
Thank you, I can take weights from OSTrack (vitb_256_mae_ce_32x4_eo300) and use your tracking/onnx export.py or do I need to make some adjustments because I see in your code convolution layers?

**Comment by lpylpy0514** [comment]
You need to rebuild the model and then export to onnx because I changed some parts of OSTrack.

**Comment by arielkantorovich** [comment]
I convert OSTrack 256 to onnx, I see there is different between the network but the input and output are the same when I try run with OpenCV I get this error:
`2.error: OpenCV(4.8.0-dev) /mnt/c/Users/arielka/PycharmProjects/VitTracker/opencv/modules/dnn/src/net_impl.cpp:1403: error: (-204:Requested object was not found) Requested blob "template" not found in function 'setInput'`

There is a way to overcome 
Your:
![your](https://github.com/lpylpy0514/workspace_tracking/assets/56262208/00f8a6b2-05f8-4877-ba86-3a172a66aa24)

OSTrack:
![OSTrack](https://github.com/lpylpy0514/workspace_tracking/assets/56262208/bc8ebe80-d4da-46fc-9a54-595655fa8032)
this problem?

Update:
If I change input output names it can work with OpenCV?
after change the names I get this error `opencv/modules/dnn/src/graph_simplifier.cpp:240: error: (-215:Assertion failed) nodeIds.find(inpName) != nodeIds.end() in function 'simplifySubgraphs'
`

**Comment by lpylpy0514** [comment]
you can try simply the model with onnxsim.simplify function. If this method doesn't work, you can go to opencv or opencv_zoo repo for more help.
